1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서1번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [1]:
import numpy as np

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:, 1])

[20 50 80]


In [4]:
print(arr[1,2])

60


In [5]:
print(arr[0:2, 0:2])

[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

arr = np.array([10, 20, 30, 40, 50, 60, 70])

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[[0,2,4]])

[10 30 50]


In [8]:
print(arr[arr > 50])

[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [9]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(sales[sales >= 200])

[200 220 300 320 310]


In [10]:
print(sales[sales[:, 2] <= 100, 0:2])

[[120 150]
 [ 50  45]]


In [12]:
print(sales[sales[:, 1] >= 150])

[[120 150 100]
 [200 180 220]
 [300 320 310]]
