In [1]:
import numpy as np
from numpy.ma.core import indices

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [6]:
q1 = np.array([200, 340, 150, 400])
q2 = np.array([220, 300, 180, 420])

total = q1+q2
print(total)

sales = np.array([q1, q2])
avg = np.mean(sales, axis=0)
print(avg)

[420 640 330 820]
[210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("덧셈: ", arr1+arr2)
print("뺄셈: ", arr1-arr2)
print("곱셈: ", arr1*arr2)
print("나눗셈: ", arr1/arr2)

덧셈:  [5 7 9]
뺄셈:  [-3 -3 -3]
곱셈:  [ 4 10 18]
나눗셈:  [0.25 0.4  0.5 ]


다음 두 배열 간의 내적 연산을 수행하세요.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("내적 연산: ", arr1 @ arr2 )

내적 연산:  32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

arr2 = np.array(arr2d)
arr1 = np.array(arr1d)

print(arr1+arr2d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

arr = np.array([10, 20, 30, 40, 50])

In [22]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])

print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())


[30 40 50]
150
50
10
30.0
