# [5] Numpy: 정렬

In [1]:
import numpy as np

### [실습 1] 1차원 배열 정렬


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.


```python
arr = np.array([50, 10, 30, 40, 20])
```

In [3]:
arr = np.array([50, 10, 30, 40, 20])

asc = np.sort(arr)

desc = np.sort(arr)[::-1]

print("오름차순 정렬: ", asc)
print("내림차순 정렬: ", desc)

오름차순 정렬:  [10 20 30 40 50]
내림차순 정렬:  [50 40 30 20 10]


### [실습 2] 2차원 배열 축 기준 정렬


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.


```python
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [4]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

row_sorted = np.sort(arr2d, axis=1)
col_sorted = np.sort(arr2d, axis=0)

print(arr2d)
print(row_sorted)
print(col_sorted)

[[8 3 5]
 [2 9 1]]
[[3 5 8]
 [1 2 9]]
[[2 3 1]
 [8 9 5]]


### [실습 3] 인덱스를 반환하는 정렬


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.


```python
arr = np.array([15, 10, 20])
```

In [5]:
arr = np.array([15, 10, 20])

sorted_idx = np.argsort(arr)

sorted_arr = arr[sorted_idx]

print("정렬된 인덱스:   ", sorted_idx)
print("인덱스로 정렬:   ", sorted_arr)

정렬된 인덱스:    [1 0 2]
인덱스로 정렬:    [10 15 20]
