# [6] Numpy: 병합

In [1]:
import numpy as np

### [실습 1] 1차원 배열 병합


다음 두 개의 1차원 배열을 `np.concatenate()`와 `np.hstack()`을 사용하여 병합하세요.


```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat_result = np.concatenate([arr1, arr2])

hstack_result = np.hstack([arr1, arr2])

print("concatenate 결과:     ", concat_result)
print("hstack 결과:          ", hstack_result)

concatenate 결과:      [1 2 3 4 5 6]
hstack 결과:           [1 2 3 4 5 6]


### [실습 2] 2차원 배열 병합


다음 두 개의 2차원 배열을 `np.concatenate()`와 `np.vstack()`을 사용하여 각각 병합하세요.


```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
```

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concat_result = np.concatenate([arr1, arr2], axis=0)

vstack_result = np.vstack([arr1, arr2])

print(concat_result)
print(vstack_result)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

 concatenate 결과 (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 vstack 결과:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
